apiVersion: apps/v1
kind: Deployment
metadata:
  name: blue
  labels:
    name: app
    app: nginxjs
    color: blue
spec:
  minReadySeconds: 30
  strategy:
    type: RollingUpdate
  replicas: 4
  selector:
    matchLabels:
      app: nginxjs
      color: blue
      name: app
  template:
    metadata:
      name: blue
      labels:
        name: app
        app: nginxjs
        color: blue
    spec:
      containers:
      - image: docker.io/mu853/citest:0bfbb6cf0f5b271d5233490e9d4e15a4a7bf6f0a
        name: blue
        ports:
          - containerPort: 80
